name: build
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install NFPM
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install -y nfpm

      - name: Build
        run: task build

      - name: Verify docs are up-to date
        run: |
          task docs:update
          git diff --exit-code

      - name: Upload Packages
        uses: actions/upload-artifact@v2
        with:
          name: deb-packages
          path: build/
